title: Data.gov Resources
email: datagov@gsa.gov
description: >-
  Resources for open data and managing your agency’s enterprise data inventory.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://resources.data.gov
twitter_username: usdatagov
github_username:  gsa
dap_agency: GSA
primary_navigation:
  - url: /federal-data-strategy/
    text: Strategy
  - url: /tools/
    text: Tools
  - text: Resources
    url: /resources/
  - text: About
    children:
      - text: History
        url: /about/history/
      - text: Requirements
        url: /about/requirements/
searchgov_affiliate: datagov-resources

github:
  organization: GSA
  repository: resources.data.gov
  default_branch: master

styles:
  - assets/uswds/css/styles.css

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
source: pages

keep_files:
  - assets/js
  - assets/uswds

exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - _js
  - _scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/