title: Federal Enterprise Data Resources
email: datagov@gsa.gov
description: >-
  Federal Enterprise Data Resources are tools, best practices, and schema standards to facilitate the adoption of open data practices across the federal government
baseurl: "/preview/18f/resources.data.gov/develop/" # the subpath of your site, e.g. /blog
twitter_username: usdatagov
github_username: 18F
dap_agency: GSA
searchgov_affiliate: datagov-resources

github:
  organization: 18F
  repository: resources.data.gov
  default_branch: develop

styles:
  - assets/uswds/css/styles.css

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
source: pages

keep_files:
  - assets/js
  - assets/uswds

exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - _js
  - _scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  resources:
    output: true
  summaries:
    output: false

resource_categories: [Data management & governance, Data tools, Skills development, Communities]
resource_tags: [open data, data converter, data schema, data standards, data inventory, data management, API, data analytics, data visualization, data validation, data cleaning, geospatial, data governance, CDO, PRA]
resource_formats: [Case study, Software tool, Standard/schema, Form/template, Report, OMB Memo, Skill-builder]
