title: Federal Enterprise Data Resources
email: datagov@gsa.gov
description: >-
  Federal Enterprise Data Resources are tools, best practices, and schema standards to facilitate the adoption of open data practices across the federal government
baseurl: "/preview/18f/resources.data.gov/develop/" # the subpath of your site, e.g. /blog
twitter_username: usdatagov
github_username: 18F
dap_agency: GSA
searchgov_affiliate: datagov-resources

github:
  organization: 18F
  repository: resources.data.gov
  default_branch: develop

scripts:
  - assets/uswds/js/uswds.min.js
  - assets/js/bundle.js

styles:
  - assets/uswds/css/styles.css

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
source: pages

keep_files:
  - assets/js
  - assets/uswds

exclude:
  - CONTRIBUTING.md
  - LICENSE.md
  - README.md
  - _js
  - _scss
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package-lock.json
  - package.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  resources:
    output: true
  summaries:
    output: false
  categories:
    output: false

page_gen:
  - index_files: false
    data: glossary
    name: term
    title: "Glossary: "

toc:
  min_level: 2
  max_level: 3
  list_class: 'usa-sidenav'
  sublist_class: 'usa-sidenav__sublist'
  item_class: 'usa-sidenav__item'
  item_prefix: 'usa-'

resource_tags: ["open data", "data converter", "data schema", "data standards", "data inventory", "data management", "API", "data analytics", "data visualization", "data validation", "data cleaning", "geospatial", "data governance", "CDO", "PRA", "ai", "data access", "data quality", "data analysis", "data sharing", "workforce development", "data governance board", "standards", "metadata", "DCAT", "inventory.data.gov", "position description", "data visualization"]

resource_formats: [Case study, Software tool, Standard/schema, Form/template, Report, OMB Memo, Skill-builder]
