title: Data.gov Resources
email: datagov@gsa.gov
description: >-
  Resources for open data and managing your agency’s enterprise data inventory.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://resources.data.gov
twitter_username: usdatagov
github_username:  gsa
primary_navigation:
  - url: /federal-data-strategy/
    text: Strategy
  - url: /tools/
    text: Tools
  - text: Resources
    children:
      - url: /case-studies/
        text: Case studies
      - url: /playbooks/
        text: Playbooks
      - url: /skill-builders/
        text: Skill builders
searchgov_affiliate: datagov-resources


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
source: pages
