backend:
  name: github
  repo: 18F/resources.data.gov
  base_url: https://federalistapp.18f.gov
  auth_endpoint: external/auth/github
  preview_context: federalist/build
  branch: netlify
  use_graphql: true

publish_mode: editorial_workflow
